### ISSUE TITLE
Insights on how to improve person detection on gazebo simulation

### ISSUE THREAD

**Issue by Rezenders** [cagbal/cob_people_object_detection_tensorflow#49]
Hello,

I'm trying to learn how to use this package for my masters project. I want to use it to detect "victims" in a flood search&rescue scenario in a gazebo simulation. I am running the default cob_people_object_detection_tensorflow node for that and the "victim" is being identified as an airplane or kite. I think the reason that this is happening is because the background is blue, if I switch to other color it is able to identify the "victim" as a person. However, I would like to maintain the background as blue for a more realistic scenario. 

I am having some doubts on how to approach this. I saw issue #27 and #32 where it was referenced some links on how to detect custom objects.  But I was wondering:

- Is it possible to remove from the default objects database everything but persons, and if by doing this the results would be better?
- Should I train to detect a custom object using images from gazebo? 
- Is it better to train from scratch or from a pre-trained model?

I would really appreciate if you could give me some insights on how to approach this issue. I thank you in advance for your attention.

Blue background:
![image](https://user-images.githubusercontent.com/20564040/82102258-62f32300-96e5-11ea-87bf-05db97952b07.png)

Green background:
![image](https://user-images.githubusercontent.com/20564040/82102420-e280f200-96e5-11ea-8066-758f505d21a7.png)

**Comment by cagbal** [comment]
Hi sorry for my late reply. The thing is that as far as I remember these models are trained on ImageNet so I guess there are no simulation people in the database but only real people. So, of course, this affects your results. 

This package is designed to be used with pre-trained models however, the TensorFlow object detection project lets us train custom models, in that case, this repo also may need some small modification. Your issues and/or PRs are appreciated. 

Each project's requirements are different, so my thoughts would be misleading. If you will only use simulation, I would train the system with simulation, because you don't need all the other imagenet object classes.

**Comment by Rezenders** [comment]
Thank you for your reply.

In the end I trained only with simulation images, I created the following dataset https://github.com/Rezenders/search-rescue_victims_dataset. I used ssd_mobilenet_v2_coco_2018_03_29 as initial checkpoint, I also used its .config file. I left it training for 12hours +- using gpu, it worked.

If anyone gets curious, the results can be seen in this [video](https://www.youtube.com/watch?v=RkESa4hbDRU&t=1s) 

Btw, thank you for this package. It is awesome.
